bootstrap_host = "$BOOTSTRAP_HOST"
bootstrap_ssh_port = "$BOOTSTRAP_SSH_PORT"
bootstrap_web_port = "$BOOTSTRAP_WEB_PORT"
bootstrap_username = "$BOOTSTRAP_USERNAME"
bootstrap_password = "$BOOTSTRAP_PASSWORD"
dcos_cluster_name = "$DCOS_CLUSTER_NAME"
custom_dcos_download_path = "$DCOS_DOWNLOAD_PATH"
local_dcos_ip_detect_script = "$DCOS_IP_DETECT_SCRIPT"
mesos_master_list = [ "$MESOS_MASTER_LIST" ]